/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tripletown;

import javax.swing.JButton;

/**
 *
 * @author Eric Hsueh
 */
public class Button extends JButton {

    /**
     * Creates new form Button
     */
    public Button(Map map, int r, int c) {
        initComponents();
        this.map = map;
        setPosition(r, c);
    }
    
    private void setPosition(int r, int c) {
        this.column = c;
        this.row = r;
    }
    
    public int getColumn() {
        return column;
    }
    
    public int getRow() {
        return row;
    }
    
    public String getImgName() {
        return imgName;
    }
    
    public void setImgName(String str) {
        this.imgName = str;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private int column;
    private int row;
    private String imgName;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        map.search(this);
    }//GEN-LAST:event_formMouseClicked

    
    Map map;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
