/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tripletown;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.io.IOException;
import java.util.Random;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author Eric Hsueh
 */
public class Map extends JFrame {

    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
        basicFrame.setSize(530, 640);
        basicFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        basicFrame.getContentPane().setLayout(new FlowLayout());
        for (int i = 0; i < 6; i++) {
            for(int j = 0; j < 6; j++) {
                JButton b = new JButton();
                setImg(b, "ground");
                b.setPreferredSize(new Dimension(80, 80));
                buttonArr[i][j] = b;
                basicFrame.add(b);
            }
        }
        setImg(nextOne, "grass");
        basicFrame.add(new JLabel("Next : "));
        basicFrame.add(nextOne);
        basicFrame.setVisible(true);
    }

    public void setImg(JButton b, String imgName) {
        try {
            Image img = ImageIO.read(getClass().getResource("../pic/" + imgName + ".png"));
            b.setIcon(new ImageIcon(img));
        }
        catch (IOException ex) {
            System.out.println("Error setting Image to Icon");
        }
    }
    
    public void randNext() {
        Random generator = new Random();
        int roll = generator.nextInt(100) + 1;
        if(roll < 50) {
            setImg(nextOne, "ground");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //private Vector<JButton> blockVec = new Vector<JButton>();
    JButton nextOne = new JButton();
    JButton[][] buttonArr = new JButton[6][6];
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicFrame = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        basicFrame.setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout basicFrameLayout = new org.jdesktop.layout.GroupLayout(basicFrame.getContentPane());
        basicFrame.getContentPane().setLayout(basicFrameLayout);
        basicFrameLayout.setHorizontalGroup(
            basicFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 533, Short.MAX_VALUE)
        );
        basicFrameLayout.setVerticalGroup(
            basicFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 474, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame basicFrame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
