/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tripletown;

import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import tripletown.Block;
/**
 *
 * @author Eric Hsueh
 */
public class Map extends Object {

    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
        basicFrame.setSize(530, 570);
        basicFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        basicFrame.getContentPane().setLayout(new FlowLayout());
        for (int i = 0; i < 36; i++) {
            JButton b = new JButton("" + i);
            b.setPreferredSize(new Dimension(80, 80));
            basicFrame.add(b);
        }
        basicFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicFrame = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        basicFrame.setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout basicFrameLayout = new org.jdesktop.layout.GroupLayout(basicFrame.getContentPane());
        basicFrame.getContentPane().setLayout(basicFrameLayout);
        basicFrameLayout.setHorizontalGroup(
            basicFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 533, Short.MAX_VALUE)
        );
        basicFrameLayout.setVerticalGroup(
            basicFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 474, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame basicFrame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
